docker pull guacamole/guacamole:latest
docker pull chronograf:latest
docker pull grafana/grafana:latest
docker pull influxdb:latest
docker pull linuxserver/mariadb:latest
docker pull nextcloud:latest
docker pull nginx:latest
docker pull phpmyadmin:latest
docker pull pihole/pihole:latest
docker pull portainer/portainer:latest
docker pull telegraf:latest
